"""
🔄 Skrypt migracji SQLite → PostgreSQL (Supabase)

Użycie:
    python migrate_sqlite_to_postgres.py export    # Eksportuje dane z SQLite
    python migrate_sqlite_to_postgres.py import    # Importuje dane do PostgreSQL
    python migrate_sqlite_to_postgres.py migrate   # Eksport + Import (wszystko na raz)

Wymagania:
    - Ustawiony DATABASE_URL w .env (PostgreSQL)
    - Uruchomione migracje Alembic (alembic upgrade head)
"""

import sys
import os
import sqlite3
import asyncio
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.orm import sessionmaker
from sqlalchemy import text
from dotenv import load_dotenv

# Load environment
load_dotenv()

SQLITE_PATH = "players.db"
EXPORT_FILE = "sqlite_export.sql"


def export_from_sqlite():
    """Eksportuje dane z SQLite do pliku SQL"""
    print("📤 Eksportuję dane z SQLite...")
    
    if not os.path.exists(SQLITE_PATH):
        print(f"❌ Nie znaleziono bazy SQLite: {SQLITE_PATH}")
        return False
    
    conn = sqlite3.connect(SQLITE_PATH)
    cursor = conn.cursor()
    
    # Pobierz listę tabel
    cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name != 'alembic_version';")
    tables = [row[0] for row in cursor.fetchall()]
    
    if not tables:
        print("⚠️  Brak tabel do eksportu (poza alembic_version)")
        conn.close()
        return False
    
    print(f"📊 Znaleziono {len(tables)} tabel: {', '.join(tables)}")
    
    with open(EXPORT_FILE, 'w', encoding='utf-8') as f:
        f.write("-- SQLite Export to PostgreSQL\n")
        f.write("-- Generated by migrate_sqlite_to_postgres.py\n\n")
        
        for table in tables:
            print(f"  📋 Eksportuję tabelę: {table}")
            
            # Pobierz schemat
            cursor.execute(f"PRAGMA table_info({table});")
            columns = [row[1] for row in cursor.fetchall()]
            
            # Pobierz dane
            cursor.execute(f"SELECT * FROM {table};")
            rows = cursor.fetchall()
            
            if not rows:
                print(f"    ⚠️  Tabela {table} jest pusta")
                continue
            
            print(f"    ✅ {len(rows)} rekordów")
            
            # Zapisz INSERT statements
            f.write(f"-- Table: {table} ({len(rows)} rows)\n")
            
            for row in rows:
                # Konwertuj wartości na PostgreSQL format
                values = []
                for val in row:
                    if val is None:
                        values.append("NULL")
                    elif isinstance(val, str):
                        # Escape single quotes
                        escaped = val.replace("'", "''")
                        values.append(f"'{escaped}'")
                    elif isinstance(val, (int, float)):
                        values.append(str(val))
                    else:
                        values.append(f"'{str(val)}'")
                
                cols = ', '.join(columns)
                vals = ', '.join(values)
                f.write(f"INSERT INTO {table} ({cols}) VALUES ({vals}) ON CONFLICT DO NOTHING;\n")
            
            f.write("\n")
    
    conn.close()
    print(f"✅ Eksport zakończony! Plik: {EXPORT_FILE}")
    return True


async def import_to_postgres():
    """Importuje dane z pliku SQL do PostgreSQL"""
    print("📥 Importuję dane do PostgreSQL...")
    
    if not os.path.exists(EXPORT_FILE):
        print(f"❌ Nie znaleziono pliku eksportu: {EXPORT_FILE}")
        print("   Uruchom najpierw: python migrate_sqlite_to_postgres.py export")
        return False
    
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        print("❌ Brak DATABASE_URL w pliku .env")
        return False
    
    if "sqlite" in database_url.lower():
        print("❌ DATABASE_URL wskazuje na SQLite! Zmień na PostgreSQL (Supabase)")
        return False
    
    print(f"🔗 Łączę z: {database_url[:50]}...")
    
    # Zamień postgresql:// na postgresql+asyncpg:// dla asyncpg driver
    if database_url.startswith("postgresql://"):
        database_url = database_url.replace("postgresql://", "postgresql+asyncpg://", 1)
    
    # Create async engine
    engine = create_async_engine(database_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    try:
        # Read SQL file
        with open(EXPORT_FILE, 'r', encoding='utf-8') as f:
            sql_content = f.read()
        
        # Split by lines and filter
        statements = [line.strip() for line in sql_content.split('\n') 
                     if line.strip() and not line.strip().startswith('--')]
        
        print(f"📄 Znaleziono {len(statements)} instrukcji SQL")
        
        # Execute statements
        async with async_session() as session:
            success_count = 0
            error_count = 0
            
            for i, stmt in enumerate(statements, 1):
                try:
                    await session.execute(text(stmt))
                    success_count += 1
                    
                    if i % 100 == 0:
                        print(f"  ⏳ Przetworzono {i}/{len(statements)} instrukcji...")
                        await session.commit()
                
                except Exception as e:
                    error_count += 1
                    if "duplicate key" not in str(e).lower():
                        print(f"  ⚠️  Błąd w instrukcji {i}: {str(e)[:100]}")
            
            # Final commit
            await session.commit()
            print(f"✅ Import zakończony!")
            print(f"   ✓ Sukces: {success_count} instrukcji")
            if error_count > 0:
                print(f"   ⚠ Pominięto: {error_count} (duplikaty lub błędy)")
        
        await engine.dispose()
        return True
    
    except Exception as e:
        print(f"❌ Błąd podczas importu: {e}")
        await engine.dispose()
        return False


async def verify_migration():
    """Weryfikuje czy migracja się powiodła"""
    print("\n🔍 Weryfikuję migrację...")
    
    database_url = os.getenv("DATABASE_URL")
    
    # Zamień postgresql:// na postgresql+asyncpg:// dla asyncpg driver
    if database_url.startswith("postgresql://"):
        database_url = database_url.replace("postgresql://", "postgresql+asyncpg://", 1)
    
    engine = create_async_engine(database_url, echo=False)
    async_session = sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)
    
    try:
        async with async_session() as session:
            # Check tables
            result = await session.execute(text("""
                SELECT table_name 
                FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name NOT LIKE 'pg_%'
                ORDER BY table_name;
            """))
            tables = [row[0] for row in result.fetchall()]
            
            print(f"\n📊 Tabele w PostgreSQL: {len(tables)}")
            
            for table in tables:
                # Count rows
                result = await session.execute(text(f"SELECT COUNT(*) FROM {table};"))
                count = result.scalar()
                print(f"  - {table}: {count} rekordów")
        
        await engine.dispose()
        print("\n✅ Weryfikacja zakończona!")
        return True
    
    except Exception as e:
        print(f"❌ Błąd podczas weryfikacji: {e}")
        await engine.dispose()
        return False


def main():
    """Main function"""
    if len(sys.argv) < 2:
        print("""
🔄 Migracja SQLite → PostgreSQL (Supabase)

Użycie:
    python migrate_sqlite_to_postgres.py export    # Eksportuje dane z SQLite
    python migrate_sqlite_to_postgres.py import    # Importuje dane do PostgreSQL
    python migrate_sqlite_to_postgres.py migrate   # Eksport + Import (wszystko)
    python migrate_sqlite_to_postgres.py verify    # Weryfikuje dane w PostgreSQL

Przed uruchomieniem:
    1. Utwórz projekt na supabase.com
    2. Dodaj DATABASE_URL do .env (PostgreSQL connection string)
    3. Uruchom migracje: alembic upgrade head
    4. Uruchom ten skrypt
""")
        return
    
    command = sys.argv[1].lower()
    
    if command == "export":
        export_from_sqlite()
    
    elif command == "import":
        asyncio.run(import_to_postgres())
    
    elif command == "migrate":
        print("🚀 Pełna migracja: Eksport + Import\n")
        if export_from_sqlite():
            print("")
            asyncio.run(import_to_postgres())
            asyncio.run(verify_migration())
    
    elif command == "verify":
        asyncio.run(verify_migration())
    
    else:
        print(f"❌ Nieznana komenda: {command}")
        print("   Dostępne: export, import, migrate, verify")


if __name__ == "__main__":
    main()
